# Generated by Django 4.1.6 on 2023-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
