# Generated by Django 4.1.6 on 2023-02-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_credits_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.clients'),
        ),
        migrations.AddField(
            model_name='credits',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.produits'),
        ),
    ]
